<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'view_helpers/panel_home' => '',
    'page_contact' => 'Contact page',
    'page_gallery' => 'Gallery page',
    'page_home' => 'Home page',
    'page_players' => 'Players page',
    'page_press' => 'Press page',
    'page_single_gallery' => 'Single gallery page',
    'page_tournament_article' => 'Tournament article page',
    'page_tournaments' => 'Tournaments page',
    'page_treners' => 'Treners page',
  ),
);


/* Auto generated by Themes Administration on : 2015.07.17 10:57:31 */
