<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_camps' => 'Camps_page',
    'page_contact' => 'Contact page',
    'page_gallery' => 'Gallery page',
    'page_home' => 'Home page',
    'page-matches' => 'Matches page',
    'page_partners' => 'Partners page',
    'page_players' => 'Players page',
    'page_press' => 'Press page',
    'page_products' => 'Products page',
    'page_single_camp' => 'Single camp page',
    'page_single_gallery' => 'Single gallery page',
    'page_post' => 'Single post page',
    'page_trener' => 'Single trener page',
    'page_tournaments' => 'Tournaments page',
    'page_treners' => 'Treners page',
  ),
);


/* Auto generated by Themes Administration on : 2015.07.22 15:35:54 */
