<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_contact' => 'Contact page',
    'page_gallery' => 'Gallery page',
    'page_home' => 'Home page',
    'page_single_gallery' => 'Single gallery page',
    'page_treners' => 'Treners page',
  ),
);


/* Auto generated by Themes Administration on : 2015.07.15 16:45:42 */
