<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => '(default page)',
    'page_about' => 'About Page',
    'page_contact' => 'Contact page',
    'page_gallery' => 'Gallery page',
    'page_guests' => 'Guests page',
    'page_home' => 'Home page',
    'page_news' => 'News',
    'page_partners' => 'Partners page',
    'page_photos' => 'Photo page',
    'page_press' => 'Press articles page',
    'page_presszone' => 'Presszone page',
    'page_single_article' => 'Single Article page',
    'page-spravodaj' => 'Spravodaj page',
    'page_videos' => 'Video page',
    'page_wrote_about_us' => 'Wrote about us page',
    404 => 'error404',
  ),
);


/* Auto generated by Themes Administration on : 2015.06.05 07:24:30 */
