<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'article' => 
  array (
    'article_normal' => 'Normal article',
  ),
  'page' => 
  array (
    'page_articles' => 'Articles page',
    'page_contact' => 'Contact page',
    'page_dropdown' => 'Dropdown',
    'page_home' => 'Home page',
    'page_normal' => 'Normal page',
    'page' => 'Page',
    'page_fotogallery' => 'Photo Gallery',
    'page_single_article' => 'Single article page',
  ),
);


/* Auto generated by Themes Administration on : 2015.02.16 15:07:46 */
