<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog' => 'Blog',
	'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'downloads' => 'Downloads',
    'gallery_page' => 'Gallery',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
  ),
  'article' => 
  array (
    'about' => 'About',
    'page_blog_post' => 'Blog Post',
  ),
);


/* Auto generated by Themes Administration on : 2014.09.08 08:03:07 */
