<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_categories' => 'Categories page',
    'form_event' => 'Formular eventu',
    'form_facility' => 'Formular sportoviska',
    'page_home' => 'Home page',
    'page_playgrounds' => 'Playgrounds page',
    'register' => 'Registrácia',
  ),
);


/* Auto generated by Themes Administration on : 2015.08.11 14:50:53 */
