<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_articles' => 'Articles page',
    'page_categories' => 'Categories page',
    'form_event' => 'Formular eventu',
    'form_facility' => 'Formular sportoviska',
    'page_gallery' => 'Gallery page',
    'page_home' => 'Home page',
    'page_club' => 'Klub',
    'page_clubs' => 'Kluby',
    'page_playgrounds' => 'Playgrounds page',
    'page_events' => 'Podujatia',
    'page_event' => 'Podujatie',
    'register' => 'Registrácia',
    'page_single_gallery' => 'Single gallery page',
    'page_single_post' => 'Single post page',
    404 => 'error_page',
    'page_playground' => 'Športovisko',
  ),
);


/* Auto generated by Themes Administration on : 2015.09.04 07:49:04 */
