<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'searching' => 'Search'
	);

$aliases = array(

	);

$disable_controller = array(
'searching'
	);



/* Auto generated by Modules Administration on : 2015.01.21 09:21:24 */
