<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['smtp_host'] = "smtp.gmail.com";
$config['smtp_user'] = "frank238238@gmail.com";
$config['smtp_pass'] = "wandrak238";
$config['smtp_port'] = "587";
$config['smtp_timeout'] = "30";
$config['protocol'] = "smtp";
$config['mailpath'] = "";
$config['charset'] = "utf-8";
$config['mailtype'] = "html";
$config['newline'] = "\r\n";


/* Auto generated by Settings Administration on : 2015.06.15 11:07:58 */
