<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => '(default page)',
    'page_about' => 'About page',
    'page_articles' => 'Articles page',
    'page_contact' => 'Contact page',
    'page1' => 'Foto page',
    'page_home' => 'Home page',
    'page_program' => 'Program page',
    'page_single_article' => 'Single article page',
    'page_single_article_video' => 'Single video page',
    'page_video' => 'Video page',
  ),
);


/* Auto generated by Themes Administration on : 2015.06.10 08:07:46 */
