<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => 'Default page',
    'page_home' => 'Home page',
    'page_contact' => 'Kontakt',
    'page_articles' => 'Články',
    'page_single_article' => 'Článok',
  ),
);


/* Auto generated by Themes Administration on : 2015.04.17 10:39:28 */
