<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_gallery' => 'Gallery page',
    'page_home' => 'Home page',
    'page_contact' => 'Kontakt',
    'page_single_gallery' => 'Single gallery page',
    'page_articles' => 'Články',
    'page_single_article' => 'Článok',
  ),
);


/* Auto generated by Themes Administration on : 2015.06.30 11:56:58 */
