<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_home' => 'Home page',
    'page_contact' => 'Kontakt',
  ),
);


/* Auto generated by Themes Administration on : 2015.04.15 15:53:04 */
