<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'home_page' => 'Homepage',
    'page_list_subpages' => 'List of articles in page',
    'page' => 'Page',
    'page_student_list' => 'Student list',
  ),
);


/* Auto generated by Themes Administration on : 2015.02.21 10:53:24 */
