<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_content' => 'Content_page',
    'home_page' => 'Homepage',
    'page_list_subpages' => 'List of articles in page',
    'page' => 'Page',
  ),
);


/* Auto generated by Themes Administration on : 2015.02.20 16:15:02 */
