<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'sfs' => 'Sfs'
	);

$aliases = array(

	);

$disable_controller = array(

	);



/* Auto generated by Modules Administration on : 2015.05.06 14:39:40 */
