<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    404 => '404',
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_maintenance' => 'Comming soon',
    'page_contact' => 'Contact',
    'page_entry' => 'Entry',
    'page_gallery' => 'Gallery',
    'page_gallery_posts' => 'Gallery posts',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'widgets/news_reader' => 'News reader',
    'page_newspaper' => 'Newspaper articles',
    'page' => 'Page',
    'rules_page' => 'Rules',
    'page_search_results' => 'Search Results',
    'sign_up_page' => 'Sign up form',
    'page_trenings_form' => 'Special trenings',
  ),
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
  ),
);


/* Auto generated by Themes Administration on : 2015.05.07 10:36:41 */
