<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'categories' => '',
    404 => '404',
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_gallery' => 'Gallery',
    'page_gallery_post' => 'Gallery single',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
    'page_search_results' => 'Search',
  ),
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
  ),
);


/* Auto generated by Themes Administration on : 2015.01.21 09:41:23 */
