<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'about-us' => 'About us',
    'careers-page' => 'Careers',
    'contact' => 'Contact',
    'homepage' => 'Home',
    'life-at-kdc' => 'Life at KDC',
    'life-at-kdc-article' => 'Life at KDC article',
    'news-article' => 'News Article',
    'success-stories' => 'Success stories',
    'success-stories-article' => 'Success story article',
    'vacancies-list' => 'Vacancies List',
    'vacancy-article' => 'Vacanty',
  ),
);


/* Auto generated by Themes Administration on : 2015.06.11 14:51:56 */
