<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'homepage' => 'Home',
    'about-us' => 'About us',
  ),
);


/* Auto generated by Themes Administration on : 2015.05.21 11:33:35 */
