<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'about-us' => 'About us',
    'contact' => 'Contact',
    'homepage' => 'Home',
  ),
);


/* Auto generated by Themes Administration on : 2015.05.21 16:02:27 */
