<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_home' => 'Home page',
  ),
);


/* Auto generated by Themes Administration on : 2015.05.20 14:26:37 */
