<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_home' => 'Home page',
    'page_news' => 'News page',
    'page_news_single_article' => 'News single article page',
    'page_rcr_positions' => 'RCR positions',
  ),
);


/* Auto generated by Themes Administration on : 2015.05.28 15:16:24 */
